### ISSUE TITLE
No module named 'zigzag.classes'

### ISSUE THREAD

**Issue by EmilySillars** [KULeuven-MICAS/stream#32]
When I run
```
python api.py
```
I get:
```
Traceback (most recent call last):
  File "/home/hoppip/stream/stream/api.py", line 2, in <module>
    from stream.classes.stages import *
  File "/home/hoppip/.local/lib/python3.12/site-packages/stream/classes/stages/__init__.py", line 1, in <module>
    from .GenerateCNWorkloadHybridStage import GenerateCNWorkloadHybridStage
  File "/home/hoppip/.local/lib/python3.12/site-packages/stream/classes/stages/GenerateCNWorkloadHybridStage.py", line 15, in <module>
    from zigzag.classes.mapping.temporal.temporal_loop import TemporalLoop
ModuleNotFoundError: No module named 'zigzag.classes'
```
- I am running inside a conda environment in which I have already run `pip install -r requirements.txt`
- using Python 3.12.3

**Comment by asyms** [comment]
Hi Emily,

I have fixed this issue and updated the api test. Keep in mind that in order to run that file you might have to first install Stream as a package in your environment by calling `pip install .` in the workspace folder.
